openapi: 3.0.0
info:
  title: SocialApp
  description: Our First social app
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: Localhost version of our app
  - url: http://staging-api.example.com
    description: demmo api for our api's

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer